# -*- coding: utf-8 -*-
"""Untitled136.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fF5qlG95ZaX5RkIJis2quMWTjeoqRK5a
"""

# conditional statement
# 3 variable => minimum value out of the same

# c logical
# conditional statement
if(False):
  print("hello")

x=10     # dynamic typed programming
if(False):
  print("hello")

x=8     # dynamic typed programming
# comparison   ,  > , >=, <=, !=, ==
if(x>=10):
  print("hello")
else:
  print("condition is false")

x=12
y=20

x>10 and  y>15

x=5
y=20
if(x>=10 and y>15):
  print("hello")
else:
  print("condition is false")

# 2 =? hey
# 5  hello
# bye
if(17%2==0):
  print("hey")
elif(17%5==0):
  print("hello")
else:
  print("bye")

'''
age>5  => Aadhar card
age>18 => aadhar card + pan link
'''

age=4
if(age>5):
  print("Aadhar card created")
  if(age>18):
    print("adhar and pan card is linked")
  else:
    print("PAN CARD NOT CREATED")
else:
  print("Age is small")

# python
# programming
# simple
# syntax
# dynamic typed
# open source
# datascience, cloud, developement, software, automation(selenium)
# testing

# python 3.8
x=10
print(type(x))

x="10"
print(type(x))

print("hey",end="-")
print("hello")